---
- name: Check Homebrew
  command: brew --version
  register: brew_check
  ignore_errors: yes
  changed_when: false

- name: Fail if Homebrew missing
  fail:
    msg: "Install Homebrew from https://brew.sh"
  when: brew_check.rc != 0

- name: Update Homebrew repository
  command: brew update
  changed_when: false

- name: Validate Envoy availability in brew
  command: brew info envoy
  register: brew_envoy_check
  failed_when: brew_envoy_check.rc != 0
  changed_when: false

- name: Install Envoy
  command: brew install envoy
  args:
    creates: "{{ '/opt/homebrew/bin/envoy' if ansible_architecture == 'arm64' else '/usr/local/bin/envoy' }}"

- name: Verify Envoy
  command: envoy --version
  register: envoy_version
  changed_when: false

- debug:
    var: envoy_version.stdout
