---
- name: Install Envoy on Debian/Ubuntu
  ansible.builtin.include_tasks: install-Debian.yml
  when: ansible_os_family == "Debian"

- name: Install Envoy on RedHat/CentOS/Rocky
  ansible.builtin.include_tasks: install-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Install Envoy on MacOS
  ansible.builtin.include_tasks: install-MacOS.yml
  when: ansible_system == "Darwin"


- name: Setup TLS directory
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/tls.yml"
  when: envoy_tls_enabled


