---
- name: Create TLS directory
  ansible.builtin.file:
    path: /etc/envoy/tls
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Check if TLS certificate exists
  ansible.builtin.stat:
    path: "{{ envoy_tls_cert_file }}"
  register: envoy_cert_stat


- name: Check if TLS private key exists
  ansible.builtin.stat:
    path: "{{ envoy_tls_key_file }}"
  register: envoy_key_stat


- name: Copy TLS certificate if not present
  ansible.builtin.copy:
    src: tls.crt
    dest: "{{ envoy_tls_cert_file }}"
    owner: root
    group: root
    mode: '0644'
  when: not envoy_cert_stat.stat.exists


- name: Copy TLS private key if not present
  ansible.builtin.copy:
    src: tls.key
    dest: "{{ envoy_tls_key_file }}"
    owner: root
    group: root
    mode: '0600'
  when: not envoy_key_stat.stat.exists
