#[envoy_servers]
#envoy-node-1 ansible_host=54.160.231.170 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abhishek/Downloads/test.pem ansible_python_interpreter=/usr/bin/python3                  
#envoy-node-2 ansible_host=13.222.160.18 ansible_user=ubuntu ansible_ssh_private_key_file=/home/abhishek/Downloads/test.pem ansible_python_interpreter=/usr/bin/python3
#envoy-node-3 ansible_host=13.218.115.171     ansible_user=ec2-user ansible_ssh_private_key_file=/home/abhishek/Downloads/test.pem ansible_python_interpreter=/usr/bin/python3
