---
- name: Validate Envoy config
  ansible.builtin.command: >
    {{ envoy_binary_path if ansible_os_family == "RedHat" else "envoy" }}
    --mode validate -c {{ envoy_config_path }}
  register: envoy_validate
  failed_when: envoy_validate.rc != 0
  changed_when: false

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Envoy
  ansible.builtin.systemd:
    name: "{{ envoy_service_name }}"
    state: restarted
