---
envoy_package_name: envoy

# Set to specific version like "1.32.2" or leave empty "" for latest
envoy_version: "1.32.2"

envoy_apt_repo_url: "https://apt.envoyproxy.io"
envoy_apt_distribution: "jammy"

envoy_keyring_path: "/etc/apt/keyrings/envoy-keyring.gpg"
envoy_repo_file: "/etc/apt/sources.list.d/envoy.list"

envoy_config_dir: "/etc/envoy"

envoy_config_path: "{{ envoy_config_dir }}/envoy.yaml"

envoy_binary_path: "{{ '/usr/local/bin/envoy' if ansible_os_family == 'RedHat' else '/usr/bin/envoy' }}"
envoy_admin_port: 9901


envoy_redhat_version: "1.32.2"

envoy_service_name: envoy

envoy_arch_map:
  x86_64: amd64
  aarch64: arm64

envoy_arch: "{{ envoy_arch_map.get(ansible_architecture, ansible_architecture) }}"

# =========================
# TLS FEATURE ADDON
# =========================

envoy_tls_enabled: true

envoy_http_port: 80
envoy_https_port: 443

envoy_tls_cert_file: "/etc/envoy/tls/tls.crt"
envoy_tls_key_file: "/etc/envoy/tls/tls.key"

# =========================
# Dynamic HA backend config
# =========================

envoy_clusters:
  - name: backend_cluster
    connect_timeout: 5s
    lb_policy: ROUND_ROBIN
    health_check_path: /health

    endpoints:
      - ip: 127.0.0.1
        port: 8080

# =========================
# HOST-BASED ROUTING DEFAULT
# =========================

envoy_virtual_hosts: []
